version: "2"

services:
  front-server:
    ports: 
      - 3000:3000
    volumes:
      - ../..:/app
      # @TODO this cache folder is for "npm" but we are using "yarn"
      - node-cache:/root/.npm
      - node-modules:/app/node_modules
    command: 
      - "yarn" 
      - "run"
      - "dev-front"       

volumes:
  node-modules:
  node-cache: