version: "3"

services:
  front-server:
    ports:
      - 3000:3000
    volumes:
      - ../..:/app
      - node-cache:/usr/local/share/.cache/yarn
      - node-modules:/app/node_modules
    command:
      - "yarn"
      - "run"
      - "dev-front"
  redis-session:
    volumes:
      - redissessiondata:/data
    ports:
      - 6379:6379
  mongo-model:
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    command: mongod --smallfiles
    volumes:
      - mongo-model-config:/data/configdb
      - mongo-model-data:/data/db
    ports:
      - 27017:27017

volumes:
  node-modules:
  node-cache:
  redissessiondata:
  mongo-model-config:
  mongo-model-data: