version: "3"

services:
  front-server:
    ports:
      - 3000:3000
    volumes:
      - ../..:/app
      - node-cache:/usr/local/share/.cache/yarn
      - node-modules:/app/node_modules
    command:
      - "yarn"
      - "run"
      - "dev-front"
  redis-session:
    volumes:
      - redissessiondata:/data
    ports:
      - 6379:6379

volumes:
  node-modules:
  node-cache:
  redissessiondata: